---
#
# Which package manager to use, options are:
#  - apk         - Alpine Linux package manager
#  - apt         - APT frontend for DEB and RPM
#  - dnf         - DNF, the new RPM frontend
#  - entropy     - Sabayon package manager
#  - packagekit  - PackageKit CLI tool
#  - pacman      - Pacman
#  - pamac       - Manjaro package manager
#  - portage     - Gentoo package manager
#  - urpmi       - Mandriva package manager
#  - yum         - Yum RPM frontend
#  - zypp        - Zypp RPM frontend

# package manager to use
backend: pacman

skip_if_no_internet: false
update_db: true
update_system: false

# pacman specific options
pacman:
    num_retries: 3
    disable_download_timeout: false
    needed_only: true
